\header {
  dedication=""
  title="Rag "U""
  subtitle=""
  subsubtitle=""
  poet=""
  meter=""
  piece=""
  composer="Marta Pujadas (2023)"
  arranger=""
  opus=""
  instrument=""
  copyright=""
  tagline=""
}