\header {
  dedication=""
  title="La Pilara"
  subtitle="(cercavila)"
  subsubtitle="grallersalsbalcons"
  poet=""
  meter=""
  piece=""
  composer="Noel Vallés"
  arranger="Font: josemanuelpenya.blogspot.com"
  opus=""
  instrument=""
  copyright="© Cafè del Centre"
  tagline=""
}