\header {
  dedication=""
  title="L’estapera"
  subtitle="Terrassa. Poblet del Vallès"
  subsubtitle=""
  poet=""
  meter=""
  piece=""
  composer="Gorramusca Víctor Pedrol"
  arranger=""
  opus=""
  instrument=""
  copyright="www.gorramusca.cat"
  tagline=""
}