\header {
  dedication=""
  title="Cromàtica"
  subtitle="Polca"
  subsubtitle=""
  poet=""
  meter=""
  piece=""
  composer="Ivó Jordà - 2015"
  arranger=""
  opus=""
  instrument=""
  copyright=""
  tagline=""
}