\header {
  dedication=""
  title="Vals del pedaç"
  subtitle=""
  subsubtitle=""
  poet=""
  meter=""
  piece=""
  composer="Marta Pujadas (2004)"
  arranger=""
  opus=""
  instrument=""
  copyright=""
  tagline=""
}