\header {
  dedication=""
  title="Processó a San Antonio Abad"
  subtitle="Ruta del Altar del Tossal de València"
  subsubtitle="Facebook: Dolçainacontraltotarotare"
  poet=""
  meter=""
  piece=""
  composer="ELS BESSONS"
  arranger="ANTONIO LLOPIS ARDID"
  opus="DOMINGO LLOPIS ARDID"
  instrument=""
  copyright=""
  tagline=""
}