\header {
  dedication=""
  title="Rumba perquè sí"
  subtitle="Rumba"
  subsubtitle=""
  poet=""
  meter=""
  piece=""
  composer="Ivó Jordà - 2011"
  arranger=""
  opus=""
  instrument=""
  copyright=""
  tagline=""
}