\header {
  dedication=""
  title="La Civila"
  subtitle=""
  subsubtitle=""
  poet=""
  meter=""
  piece=""
  composer="Marta Pujadas (2011)"
  arranger=""
  opus=""
  instrument=""
  copyright=""
  tagline=""
}