\header {
  dedication=""
  title="Ballet de muntanya"
  subtitle="2a veu de Liv Hallum"
  subsubtitle=""
  poet=""
  meter=""
  piece=""
  composer="Gorramusca Víctor Pedrol"
  arranger=""
  opus=""
  instrument=""
  copyright="www.gorramusca.cat"
  tagline=""
}