\header {
  dedication=""
  title="Tocs Occitans"
  subtitle=""
  subsubtitle=""
  poet=""
  meter=""
  piece=""
  composer="Els Berros de la cort"
  arranger="Arr. Pol Ducable"
  opus=""
  instrument=""
  copyright="Ministrers de l'Aixada"
  tagline=""
}