\header {
  dedication=""
  title="Gener"
  subtitle="Facebook: Dolçainacontraltotarotare"
  subsubtitle=""
  poet="Original per a gralla"
  meter="Arranj. Xavi Richart"
  piece=""
  composer="Manel Rius"
  arranger=""
  opus=""
  instrument=""
  copyright=""
  tagline=""
}