\header {
  dedication=""
  title="Ball del Pota-roig"
  subtitle=""
  subsubtitle=""
  poet=""
  meter=""
  piece=""
  composer="Erola Ramis Rovira"
  arranger="Músiques de Castellbisbal"
  opus=""
  instrument=""
  copyright=""
  tagline=""
}