\header {
  dedication=""
  title="Jump at the sun - Jig"
  subtitle="John Kirkpatrick - Anglaterra"
  subsubtitle=""
  poet=""
  meter=""
  piece=""
  composer="Gorramusca Víctor Pedrol"
  arranger=""
  opus=""
  instrument=""
  copyright="www.gorramusca.cat"
  tagline=""
}