\header {
  dedication=""
  title="Santa Maria Strela do día"
  subtitle="Facebook: Dolçainacontraltotarotare"
  subsubtitle=""
  poet=""
  meter=""
  piece=""
  composer="Cantigas de Santa María"
  arranger="Alfonso X - cantiga 100"
  opus=""
  instrument=""
  copyright=""
  tagline=""
}