\header {
  dedication=""
  title="El Cafè del Centre"
  subtitle="(pasdoble de la Inauguració)"
  subsubtitle=""
  poet=""
  meter=""
  piece=""
  composer="Cesc Alexandri, 2006"
  arranger="(versió amb baixa: març, 2011)"
  opus=""
  instrument=""
  copyright=""
  tagline=""
}