\header {
  dedication=""
  title="Sota un temps de pluja"
  subtitle="Pasdoble"
  subsubtitle=""
  poet=""
  meter=""
  piece=""
  composer="Ivó Jordà - 2013"
  arranger=""
  opus=""
  instrument=""
  copyright=""
  tagline=""
}