\header {
  dedication=""
  title="Si em mires"
  subtitle=""
  subsubtitle=""
  poet=""
  meter=""
  piece=""
  composer="Marta Pujadas (2014)"
  arranger=""
  opus=""
  instrument=""
  copyright=""
  tagline=""
}