\header {
  dedication=""
  title="Bolero infernal"
  subtitle="(Ball dels Diables de"
  subsubtitle="Palau-solità i Plegamans)"
  poet=""
  meter=""
  piece=""
  composer="Cesc Alexandri, 2012"
  arranger=""
  opus=""
  instrument=""
  copyright=""
  tagline=""
}