\header {
  dedication=""
  title="Sant Antoni L´Ermita"
  subtitle="Facebook: Dolçainacontraltotarotare"
  subsubtitle=""
  poet=""
  meter=""
  piece=""
  composer=""
  arranger=""
  opus=""
  instrument=""
  copyright=""
  tagline=""
}