\header {
  dedication=""
  title="Processó a San Vicent Ferrer"
  subtitle="Dedicada al Altar del Tossal de València"
  subsubtitle="Facebook: Dolçainacontraltotarotare"
  poet=""
  meter=""
  piece=""
  composer="ANTONIO LLOPIS ARDID"
  arranger="DOMINGO LLOPIS ARDID"
  opus="ELS BESSONS"
  instrument=""
  copyright=""
  tagline=""
}