\header {
  dedication=""
  title="El Baliga"
  subtitle="Pasdoble"
  subsubtitle=""
  poet=""
  meter=""
  piece=""
  composer="Ivó Jordà - 2012"
  arranger=""
  opus=""
  instrument=""
  copyright=""
  tagline=""
}