\header {
  dedication=""
  title="Jota de passeig"
  subtitle="Adaptació de l'original per a sac de gemecs"
  subsubtitle=""
  poet=""
  meter=""
  piece=""
  composer="Ivó Jordà - 2015"
  arranger=""
  opus=""
  instrument=""
  copyright=""
  tagline=""
}