\header {
  dedication=""
  title="Xotis d’en Jaumet Xic"
  subtitle="Jaumet Xic"
  subsubtitle=""
  poet=""
  meter=""
  piece=""
  composer="Gorramusca Víctor Pedrol"
  arranger=""
  opus=""
  instrument=""
  copyright="www.gorramusca.cat"
  tagline=""
}