\header {
  dedication=""
  title="Procesión a los Santos Juanes"
  subtitle="Ruta del Altar del Tossal de Valéncia"
  subsubtitle="Facebook: Dolçainacontraltotarotare"
  poet=""
  meter=""
  piece=""
  composer="Domingo Llopis Ardid"
  arranger="Antonio Llopis Ardid"
  opus=""
  instrument=""
  copyright=""
  tagline=""
}