\header {
  dedication=""
  title="La Bamba"
  subtitle=""
  subsubtitle=""
  poet=""
  meter=""
  piece=""
  composer="Arr. Ivó Jordà - 2013"
  arranger=""
  opus=""
  instrument=""
  copyright=""
  tagline=""
}