\header {
  dedication=""
  title="Ding, Dang, Dong"
  subtitle="Facebook: Dolçainacontraltotarotare"
  subsubtitle=""
  poet=""
  meter=""
  piece=""
  composer="Veu Contralto"
  arranger="Domingo Llopis Ardid"
  opus="Antonio Llopis Ardid"
  instrument=""
  copyright=""
  tagline=""
}