\header {
  dedication=""
  title="Neska zaharrak – arin-arina"
  subtitle="Euskal Herria"
  subsubtitle=""
  poet=""
  meter=""
  piece=""
  composer="Gorramusca Víctor Pedrol"
  arranger=""
  opus=""
  instrument=""
  copyright="www.gorramusca.cat"
  tagline=""
}