\header {
  dedication=""
  title="Niña hechicera"
  subtitle="(masurca)"
  subsubtitle="grallersalsbalcons"
  poet=""
  meter=""
  piece=""
  composer="Font: Punt de Trobada, Vol. 1"
  arranger=""
  opus=""
  instrument=""
  copyright="© Cafè del Centre"
  tagline=""
}