\header {
  dedication=""
  title="Marxa del Sant Gitano"
  subtitle=""
  subsubtitle=""
  poet=""
  meter=""
  piece=""
  composer="Cesc Alexandri, març de 2004"
  arranger=""
  opus=""
  instrument=""
  copyright=""
  tagline=""
}