\header {
  dedication=""
  title="El Cerro de la Silla - xotis"
  subtitle="Mèxic"
  subsubtitle=""
  poet=""
  meter=""
  piece=""
  composer="Gorramusca Víctor Pedrol"
  arranger=""
  opus=""
  instrument=""
  copyright="www.gorramusca.cat"
  tagline=""
}