\header {
  dedication=""
  title="La Castellera"
  subtitle="Pasdoble"
  subsubtitle=""
  poet=""
  meter=""
  piece=""
  composer="Ivó Jordà - 2010"
  arranger=""
  opus=""
  instrument=""
  copyright=""
  tagline=""
}