\header {
  dedication=""
  title="Rumba"
  subtitle=""
  subsubtitle="grallersalsbalcons"
  poet=""
  meter=""
  piece=""
  composer="Camilo Ronzano"
  arranger="Font: fqll.es/catalogo_detalle.php?id=2549"
  opus=""
  instrument=""
  copyright="© Cafè del Centre"
  tagline=""
}