\header {
  dedication=""
  title="Revolts"
  subtitle=""
  subsubtitle=""
  poet=""
  meter=""
  piece=""
  composer="Marta Pujadas (gener 2023)"
  arranger=""
  opus=""
  instrument=""
  copyright=""
  tagline=""
}