<?php
$labels=array(
	"title"=>"__COUNT2__ partitures i cançons per a gralla en __COUNT1__ gèneres",
	"author"=>"Josep Sanz Campderrós",
	"description"=>"Plana web amb aplicació per veure partitures i cançons, escoltar-ho tot o per veus, descarregar-se les fonts per lilypond, pdf, midis o mp3s, cercar per paraules claus a les metadades, ...",
	"keywords"=>"partitures, cançons, gralla, frescobaldi, lilypond, timidity, lame, pdf, midi, mp3",
	"search"=>"Cercar",
	"results"=>"Resultats de la cerca",
	"found01"=>"No s'ha trobat cap resultat amb la paraula __TEXT__",
	"found02"=>"No s'ha trobat cap resultat amb les paraules __TEXT__",
	"found11"=>"S'ha trobat __NUM__ resultat amb la paraula __TEXT__",
	"found12"=>"S'ha trobat __NUM__ resultat amb les paraules __TEXT__",
	"found21"=>"S'han trobat __NUM__ resultats amb la paraula __TEXT__",
	"found22"=>"S'han trobat __NUM__ resultats amb les paraules __TEXT__",
	"about"=>"Envers a ...",
	"ly"=>"Fitxer font per Lilypond",
	"pdf"=>"Fitxer de document PDF",
	"midi"=>"Fitxer de seqüència MIDI",
	"mp3"=>"Fitxer de so MP3",
	"pista0"=>" per totes les pistes",
	"pista1"=>" per la pista __NUM__",
	"type"=>"Tipus",
	"file"=>"Fitxer",
	"size"=>"Mida",
	"play"=>"Escoltar",
	"play2"=>"Reproduir",
	"pause2"=>"Pausar",
	"stop2"=>"Parar",
	"repo"=>"https://github.com/josepsanzcamp/gralla",
	"site"=>"https://gralla.josepsanz.net/",
);
?>