\header {
  dedication=""
  title="Mirant amunt"
  subtitle="Vals-Jota"
  subsubtitle=""
  poet=""
  meter=""
  piece=""
  composer="Autor: Felip Morales"
  arranger=""
  opus=""
  instrument=""
  copyright=""
  tagline=""
}