\header {
  dedication=""
  title="Ball de la Maniera"
  subtitle="Popular"
  subsubtitle=""
  poet=""
  meter=""
  piece=""
  composer="Arranjament: Oriol Pidelaserra"
  arranger="Músiques de Castellbisbal"
  opus=""
  instrument=""
  copyright=""
  tagline=""
}